Chrstian Base Features
cmdevoto/event-planner pull request #7
Opened 2021-05-16 22:46 UTC by c-amstutz

Yeah so this should've been done a week ago

2021-05-16 23:53 UTC, cmdevoto approved these changes
looks great!

2021-05-16 23:53 UTC, cmdevoto commented on eventPlannerApp/modules/events/editEventPage.py
> +class EditEventForm(FlaskForm):
this is intriguing me

2021-05-16 23:58 UTC, cmdevoto requested changes

2021-05-16 23:58 UTC, cmdevoto commented on eventPlannerApp/modules/events/editEventPage.py
> +@bp.route('/event/edit/<int:eventId>', methods=['GET', 'POST'])
this just needs login required

2021-05-16 23:58 UTC, cmdevoto commented on eventPlannerApp/modules/events/editEventPage.py
> +@bp.route('/event/edit/<int:eventId>', methods=['GET', 'POST'])
on that same thought, do we want to consider if everyone can edit or view event pages? should we have a way to stop people from accessing the url of private events?

2021-05-16 23:58 UTC, cmdevoto commented on eventPlannerApp/modules/events/editEventPage.py
> +@bp.route('/event/edit/<int:eventId>', methods=['GET', 'POST'])
also should it be that anyone invited to an event can edit?

2021-05-17 01:40 UTC, bdivney approved these changes

2021-05-17 01:40 UTC, merged